#!/bin/bash

set -euxo pipefail

cd "$HOME"

# Update submodules
yadm submodule update --recursive --init


# Symlink private dirs from keybase
if [ -d .keybase/secrets ]; then
  rm -rf ~/.ssh && ln -sf .keybase/secrets/.ssh
  rm -rf ~/.aws && ln -sf .keybase/secrets/.aws
  rm -rf .gnupg && ln -sf .keybase/secrets/.gnupg
fi

# TODO: Invoke brew bundle on Mac

yadm remote set-url origin "git@github.com:deepakjois/yadm.git"
